// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	ReqData              map[string]string `protobuf:"bytes,1,rep,name=req_data,json=reqData,proto3" json:"req_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Method               string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetReqData() map[string]string {
	if m != nil {
		return m.ReqData
	}
	return nil
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterMapType((map[string]string)(nil), "pb.Request.ReqDataEntry")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0xe5, 0x98, 0x5e, 0x38, 0xcd, 0x80, 0x8e, 0x10, 0xb2, 0x3a, 0x45, 0x5d, 0xe8, 0x94,
	0xa1, 0x5d, 0x50, 0xe7, 0xf2, 0x02, 0xe6, 0x01, 0x90, 0xd3, 0x1c, 0x81, 0x04, 0x8e, 0x1d, 0xdb,
	0x8d, 0x94, 0xd7, 0xe0, 0x89, 0x91, 0x2f, 0x43, 0x26, 0xff, 0x9f, 0xfd, 0x7f, 0xbe, 0x41, 0x7d,
	0x33, 0x5a, 0x9b, 0xa1, 0xb5, 0xce, 0x04, 0x83, 0x95, 0xed, 0x0e, 0x7f, 0x0c, 0x36, 0x92, 0xc6,
	0x3b, 0xf9, 0x80, 0x67, 0xd8, 0x3a, 0x1a, 0x3f, 0x7b, 0x15, 0x94, 0x60, 0x0d, 0x3f, 0xee, 0x4e,
	0xa2, 0xb5, 0x5d, 0x5b, 0x96, 0xe3, 0x78, 0x55, 0x41, 0xbd, 0x0f, 0xc1, 0xcd, 0x72, 0xe3, 0x32,
	0xe1, 0x0b, 0xac, 0x35, 0x85, 0x6f, 0xd3, 0x8b, 0xaa, 0x61, 0xc7, 0x47, 0x59, 0x68, 0x7f, 0x81,
	0x7a, 0x29, 0xe0, 0x13, 0xf0, 0x1f, 0x9a, 0x05, 0x4b, 0xa5, 0x18, 0xf1, 0x19, 0x56, 0x93, 0xfa,
	0xbd, 0x53, 0x11, 0x33, 0x5c, 0xaa, 0x37, 0x76, 0xb8, 0xc2, 0x56, 0x92, 0xb7, 0x66, 0xf0, 0x84,
	0x08, 0x0f, 0x37, 0xd3, 0x53, 0x12, 0x57, 0x32, 0xe5, 0xb8, 0x97, 0xf6, 0x5f, 0xc5, 0x8b, 0x31,
	0xb6, 0xd2, 0xb5, 0x79, 0x9a, 0x4a, 0xf9, 0xf4, 0x0a, 0xfc, 0xc3, 0x4d, 0xd8, 0x00, 0x97, 0x34,
	0xe2, 0x6e, 0xf1, 0x94, 0x7d, 0x9d, 0x21, 0x1f, 0xd1, 0xad, 0xd3, 0x77, 0x9c, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x88, 0x66, 0x43, 0x14, 0x1e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SrvClient is the client API for Srv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SrvClient interface {
	Req(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type srvClient struct {
	cc *grpc.ClientConn
}

func NewSrvClient(cc *grpc.ClientConn) SrvClient {
	return &srvClient{cc}
}

func (c *srvClient) Req(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Srv/Req", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvServer is the server API for Srv service.
type SrvServer interface {
	Req(context.Context, *Request) (*Response, error)
}

// UnimplementedSrvServer can be embedded to have forward compatible implementations.
type UnimplementedSrvServer struct {
}

func (*UnimplementedSrvServer) Req(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Req not implemented")
}

func RegisterSrvServer(s *grpc.Server, srv SrvServer) {
	s.RegisterService(&_Srv_serviceDesc, srv)
}

func _Srv_Req_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvServer).Req(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Srv/Req",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvServer).Req(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Srv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Srv",
	HandlerType: (*SrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Req",
			Handler:    _Srv_Req_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}
